"""Real-time signal generation engine — Phase 5 core.

Maintains a rolling window of bar data, runs validated strategies on each
new bar, and emits trade signals when entry/exit conditions are met.

Two operating modes:
  1. **Live** — receives bars from a data feed callback via ``on_bar()``.
  2. **Replay** — processes historical data bar-by-bar for integration testing.

Performance notes:
  - The bar buffer is a plain ``list[dict]`` appended in O(1); only the
    tail ``lookback_bars`` are kept, trimmed every 100 bars to amortise
    the cost.
  - A single ``pl.DataFrame`` is materialised from the buffer once per bar,
    then shared across all strategies.
  - Signal column reads on the last row use Polars ``.row(-1)`` which
    avoids a full-column materialisation.
"""

import logging
import time
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime
from threading import Event
from typing import Any, Callable

import polars as pl

logger = logging.getLogger(__name__)

# Column names the Strategy protocol must produce.
_SIGNAL_COLS = ("entry_long", "entry_short", "exit_long", "exit_short")

# How often (in bars) we compact the buffer to exactly ``lookback_bars``.
_TRIM_INTERVAL = 100


# ── Data classes ─────────────────────────────────────────────────────


@dataclass
class Signal:
    """A trade signal generated by the engine."""

    timestamp: datetime
    strategy_name: str
    direction: str  # "long" or "short"
    signal_type: str  # "entry" or "exit"
    price: float  # Current price at signal time
    stop_loss: float | None = None
    take_profit: float | None = None
    contracts: int = 1
    confidence: float = 1.0  # 0-1, based on how many strategies agree
    metadata: dict = field(default_factory=dict)


@dataclass
class EngineState:
    """Observable snapshot of the signal engine."""

    is_running: bool = False
    strategies_loaded: int = 0
    bars_processed: int = 0
    signals_generated: int = 0
    last_bar_time: datetime | None = None
    last_signal_time: datetime | None = None
    errors: list[str] = field(default_factory=list)


# ── Signal Engine ────────────────────────────────────────────────────


class SignalEngine:
    """
    Real-time signal generation engine.

    Usage::

        engine = SignalEngine(
            strategies=[strategy1, strategy2],
            risk_manager=rm,
            contract_spec=MNQ_SPEC,
            account_state=account,
            prop_rules=prop_rules,
        )

        # Register signal handlers
        engine.on_signal(my_callback)

        # Replay mode (for testing)
        engine.replay(historical_data, speed=1.0)

        # Live mode
        engine.start()
        engine.on_bar(new_bar)  # called by data feed
    """

    def __init__(
        self,
        strategies: list,
        risk_manager,
        contract_spec,
        account_state,
        prop_rules,
        lookback_bars: int = 500,
        primary_timeframe: str = "1m",
    ):
        self.strategies = strategies
        self.risk_manager = risk_manager
        self.contract_spec = contract_spec
        self.account_state = account_state
        self.prop_rules = prop_rules
        self.lookback_bars = lookback_bars
        self.primary_timeframe = primary_timeframe

        # Rolling bar buffer — append-only list trimmed periodically.
        self._bar_buffer: list[dict] = []
        self._bars_since_trim: int = 0

        # Signal history — bounded deque so memory stays flat.
        self._recent_signals: deque[Signal] = deque(maxlen=200)

        # External callbacks invoked on each new signal.
        self._signal_handlers: list[Callable[[Signal], None]] = []

        # Engine state (observable externally).
        self.state = EngineState(strategies_loaded=len(strategies))

        # Stop flag for controlled shutdown.
        self._stop_event = Event()

    # ── Public API ───────────────────────────────────────────────────

    def on_signal(self, handler: Callable[[Signal], None]) -> None:
        """Register a callback for when signals are generated."""
        self._signal_handlers.append(handler)

    def on_bar(self, bar: dict) -> None:
        """
        Process a new bar from the data feed.

        ``bar`` must contain at minimum:
          timestamp, open, high, low, close, volume

        Hot path — called once per bar (e.g. every minute).
        """
        if not self.state.is_running:
            return

        try:
            self._ingest_bar(bar)
            df = self._build_dataframe()
            if df is None:
                return

            # Wrap in the dict[str, DataFrame] structure strategies expect.
            data_dict: dict[str, pl.DataFrame] = {self.primary_timeframe: df}

            # Collect signals across all strategies for consensus scoring.
            bar_signals: list[Signal] = []
            for strategy in self.strategies:
                signals = self._run_strategy(strategy, data_dict)
                bar_signals.extend(signals)

            # Score confidence when multiple strategies agree.
            if len(self.strategies) > 1:
                self._score_confidence(bar_signals)

            for sig in bar_signals:
                self._emit_signal(sig)

        except Exception as exc:
            msg = f"on_bar error: {exc}"
            logger.exception(msg)
            self.state.errors.append(msg)

    def start(self) -> None:
        """Mark the engine as running and ready to receive bars."""
        self._stop_event.clear()
        self.state.is_running = True
        self.state.errors = []
        logger.info(
            "SignalEngine started — %d strategies, lookback=%d",
            len(self.strategies),
            self.lookback_bars,
        )

    def stop(self) -> None:
        """Stop the engine. No further bars will be processed."""
        self._stop_event.set()
        self.state.is_running = False
        logger.info(
            "SignalEngine stopped — %d bars processed, %d signals generated",
            self.state.bars_processed,
            self.state.signals_generated,
        )

    def replay(
        self,
        data: pl.DataFrame,
        speed: float = 0.0,
        callback: Callable | None = None,
    ) -> list[Signal]:
        """
        Replay historical data bar-by-bar through the engine.

        Args:
            data: Historical OHLCV DataFrame to replay.
            speed: Delay between bars in seconds (0 = as fast as possible).
            callback: Called after each bar with
                      ``(bar_index, total_bars, signals_this_bar)``.

        Returns:
            All signals generated during the replay.
        """
        self._bar_buffer.clear()
        self._bars_since_trim = 0
        self._recent_signals.clear()
        self.state = EngineState(strategies_loaded=len(self.strategies))
        self.start()

        all_signals: list[Signal] = []
        rows = data.to_dicts()
        total = len(rows)

        for idx, row in enumerate(rows):
            if self._stop_event.is_set():
                break

            signals_before = self.state.signals_generated
            self.on_bar(row)
            signals_after = self.state.signals_generated

            bar_signals = list(self._recent_signals)[
                -(signals_after - signals_before) :
            ] if signals_after > signals_before else []
            all_signals.extend(bar_signals)

            if callback is not None:
                callback(idx, total, bar_signals)

            if speed > 0:
                time.sleep(speed)

        self.stop()
        return all_signals

    def get_state(self) -> EngineState:
        """Return a snapshot of the current engine state."""
        return self.state

    def get_recent_signals(self, n: int = 20) -> list[Signal]:
        """Return the *n* most recent signals (newest last)."""
        signals = list(self._recent_signals)
        return signals[-n:]

    # ── Internal: bar management ─────────────────────────────────────

    def _ingest_bar(self, bar: dict) -> None:
        """Append bar to the rolling buffer and update bookkeeping."""
        self._bar_buffer.append(bar)
        self._bars_since_trim += 1

        # Periodic trim keeps memory bounded without per-bar list slicing.
        if self._bars_since_trim >= _TRIM_INTERVAL:
            overflow = len(self._bar_buffer) - self.lookback_bars
            if overflow > 0:
                del self._bar_buffer[:overflow]
            self._bars_since_trim = 0

        self.state.bars_processed += 1

        ts = bar.get("timestamp")
        if isinstance(ts, datetime):
            self.state.last_bar_time = ts
        elif ts is not None:
            # Attempt to parse string timestamps.
            try:
                self.state.last_bar_time = datetime.fromisoformat(str(ts))
            except (ValueError, TypeError):
                pass

    def _build_dataframe(self) -> pl.DataFrame | None:
        """
        Materialise a Polars DataFrame from the bar buffer.

        Returns ``None`` if there are too few bars for any strategy to
        produce meaningful signals (< 2 bars).
        """
        if len(self._bar_buffer) < 2:
            return None

        try:
            return pl.DataFrame(self._bar_buffer)
        except Exception as exc:
            msg = f"DataFrame build error: {exc}"
            logger.error(msg)
            self.state.errors.append(msg)
            return None

    # ── Internal: strategy execution ─────────────────────────────────

    def _run_strategy(
        self,
        strategy,
        data: dict[str, pl.DataFrame],
    ) -> list[Signal]:
        """
        Run a single strategy and extract signals from the latest bar.

        Returns a (possibly empty) list of ``Signal`` objects.
        """
        try:
            df = strategy.compute_signals(data)
        except Exception as exc:
            msg = f"Strategy {getattr(strategy, 'name', '?')} compute error: {exc}"
            logger.error(msg)
            self.state.errors.append(msg)
            return []

        return self._check_signals(df, strategy)

    def _check_signals(self, df: pl.DataFrame, strategy) -> list[Signal]:
        """
        Inspect the *last row* of a signal DataFrame for entry/exit flags.

        Only the most recent bar matters — earlier bars were already
        processed on prior calls.
        """
        signals: list[Signal] = []

        # Validate required columns exist.
        present_cols = set(df.columns)
        for col in _SIGNAL_COLS:
            if col not in present_cols:
                return signals

        # Read the last row as a dict — single allocation.
        last_idx = df.height - 1
        last_row = df.row(last_idx, named=True)

        ts_raw = last_row.get("timestamp")
        ts = self._coerce_timestamp(ts_raw)
        price = float(last_row.get("close", 0.0))
        strategy_name: str = getattr(strategy, "name", "unknown")

        # --- Entry signals ---------------------------------------------------
        if last_row.get("entry_long"):
            sig = self._make_entry_signal(
                strategy, strategy_name, ts, price, "long"
            )
            if sig is not None:
                signals.append(sig)

        if last_row.get("entry_short"):
            sig = self._make_entry_signal(
                strategy, strategy_name, ts, price, "short"
            )
            if sig is not None:
                signals.append(sig)

        # --- Exit signals ----------------------------------------------------
        if last_row.get("exit_long"):
            signals.append(
                Signal(
                    timestamp=ts,
                    strategy_name=strategy_name,
                    direction="long",
                    signal_type="exit",
                    price=price,
                )
            )

        if last_row.get("exit_short"):
            signals.append(
                Signal(
                    timestamp=ts,
                    strategy_name=strategy_name,
                    direction="short",
                    signal_type="exit",
                    price=price,
                )
            )

        return signals

    def _make_entry_signal(
        self,
        strategy,
        strategy_name: str,
        ts: datetime,
        price: float,
        direction: str,
    ) -> Signal | None:
        """
        Build an entry ``Signal`` if the risk manager allows the trade.

        Queries the strategy for stop-loss, take-profit, and position size,
        then runs the risk manager pre-trade check.  Returns ``None`` when
        the trade is rejected.
        """
        # Position sizing.
        contracts = 1
        if hasattr(strategy, "get_position_size"):
            try:
                contracts = strategy.get_position_size(
                    self.account_state,
                    self.contract_spec,
                    self.prop_rules,
                )
            except Exception as exc:
                logger.warning("Position size error (%s): %s", strategy_name, exc)

        # Risk gate.
        try:
            allowed, reason = self.risk_manager.pre_trade_check(
                ts, direction, contracts, self.account_state,
            )
        except Exception as exc:
            msg = f"Risk check error ({strategy_name}): {exc}"
            logger.error(msg)
            self.state.errors.append(msg)
            return None

        if not allowed:
            logger.debug(
                "Signal rejected — %s %s %s: %s",
                strategy_name, direction, ts, reason,
            )
            return None

        # Stop loss / take profit.
        stop_loss: float | None = None
        take_profit: float | None = None
        if hasattr(strategy, "get_stop_loss"):
            try:
                stop_loss = strategy.get_stop_loss(price, direction)
            except Exception:
                pass
        if hasattr(strategy, "get_take_profit"):
            try:
                take_profit = strategy.get_take_profit(price, direction)
            except Exception:
                pass

        return Signal(
            timestamp=ts,
            strategy_name=strategy_name,
            direction=direction,
            signal_type="entry",
            price=price,
            stop_loss=stop_loss,
            take_profit=take_profit,
            contracts=contracts,
            metadata={"risk_reason": reason},
        )

    # ── Internal: consensus & emission ───────────────────────────────

    def _score_confidence(self, signals: list[Signal]) -> None:
        """
        When multiple strategies are loaded, score entry signal confidence
        based on directional agreement.

        Confidence = (# strategies signalling this direction) / (# total strategies).
        Mutates the ``confidence`` field in place.
        """
        if not signals:
            return

        n_strategies = len(self.strategies)
        if n_strategies <= 1:
            return

        # Count entry agreements per direction.
        entry_counts: dict[str, int] = {}
        for sig in signals:
            if sig.signal_type == "entry":
                entry_counts[sig.direction] = (
                    entry_counts.get(sig.direction, 0) + 1
                )

        for sig in signals:
            if sig.signal_type == "entry":
                agree = entry_counts.get(sig.direction, 1)
                sig.confidence = round(agree / n_strategies, 4)

    def _emit_signal(self, signal: Signal) -> None:
        """Persist the signal and fan out to all registered handlers."""
        self._recent_signals.append(signal)
        self.state.signals_generated += 1
        self.state.last_signal_time = signal.timestamp

        logger.info(
            "SIGNAL  %s  %s  %s  %.2f  sl=%s  tp=%s  qty=%d  conf=%.2f",
            signal.strategy_name,
            signal.signal_type,
            signal.direction,
            signal.price,
            signal.stop_loss,
            signal.take_profit,
            signal.contracts,
            signal.confidence,
        )

        for handler in self._signal_handlers:
            try:
                handler(signal)
            except Exception as exc:
                msg = f"Signal handler error: {exc}"
                logger.error(msg)
                self.state.errors.append(msg)

    # ── Helpers ──────────────────────────────────────────────────────

    @staticmethod
    def _coerce_timestamp(raw: Any) -> datetime:
        """Best-effort conversion of a raw value to ``datetime``."""
        if isinstance(raw, datetime):
            return raw
        if raw is not None:
            try:
                return datetime.fromisoformat(str(raw))
            except (ValueError, TypeError):
                pass
        return datetime.now()
